trigger:
- allegrex

jobs:
  - job: linux_build
    displayName: Linux build
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
        
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build
      displayName: Install build tools

    - script: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_TARGETS_TO_BUILD="Mips" -DLLVM_ENABLE_PROJECTS="clang;lld" ../llvm/
      displayName: 'Configure'
    
    - script: |
        cd build
        cmake --build . --config Debug --parallel 4
      displayName: 'Build'
    
    - publish: $(System.DefaultWorkingDirectory)/build/
      displayName: 'Publish artifacts'