trigger:
- allegrex

jobs:
  - job: windows_build
    displayName: Windows build
    timeoutInMinutes: 0
    pool:
      vmImage: 'windows-2019'
    
    steps:
    - powershell: |
        mkdir build
        cd build
        cmake -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="Mips" -DLLVM_ENABLE_PROJECTS="clang;lld" ../llvm/
      displayName: 'Configure'

    - powershell: |
        cd build
        cmake --build . --config Release
      displayName: 'Build'
    
    - publish: $(System.DefaultWorkingDirectory)/build/
      displayName: 'Publish artifacts'

  - job: linux_build
    displayName: Linux build
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
        
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build
      displayName: Install build tools

    - script: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="Mips" -DLLVM_ENABLE_PROJECTS="clang;lld" ../llvm/
      displayName: 'Configure'
    
    - script: |
        cd build
        cmake --build . --config Release --parallel 4
      displayName: 'Build'
    
    - publish: $(System.DefaultWorkingDirectory)/build/
      displayName: 'Publish artifacts'